# Build seems to work better if we pin things to be consistent across different
# builds

# We don't have any particular python requirement, just that it doesn't change from
# one package to the next. This is the version in dep-test-pixi environment created
# by make dep-test-env, which is a  consistent set
python:
  - ==3.13.7

# Hold numpy fixed. We don't actually have any particular constraint
# on the numpy version, but we need to have the same one used for all
# the packages. 
numpy:
  - ==2.3.3

# Any version of blas is fine, however we sometimes run into switching
# from a openblas to mkl version (build with one, run with the
# other). Hold this fixed to openblas so we don't have a issue
libblas:
  - "* *openblas"

# Swig 4.4.0 just came out, and doesn't seem to work. We'll fix this
# at some point, but for now restrict ourselves to the older version of swig
swig:
  - <4.4.0
  
# We don't require a certain boost version, but we do require this to
# be consistent. It seems like the packages should pin them automatically,
# but they don't seem to. So we determined a consistent boost version
# (from dep-test-pixi), and grabbed that version. This can be updated at
# any time
boost:
  - ~= 1.84.0
