context:
  name: afids-data
  version: 1.12
  
package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: https://github.com/Cartography-jpl/${{ name }}.git
    tag: ${{ version }}

build:
  number: 0
  noarch: generic
  script:
    - ./configure --prefix=$PREFIX
    - make all
    - make install
    - mkdir -p $PREFIX/bin/
    - cp $RECIPE_DIR/afids-data-post-link.sh $PREFIX/bin/.afids-data-post-link.sh
    - cp $RECIPE_DIR/afids-data-post-link.py $PREFIX/bin/.afids-data-post-link.py
    - cp $RECIPE_DIR/readme_for_install $PREFIX/data/README
    - cat $RECIPE_DIR/extra_for_setup $PREFIX/data/setup_afids_data.sh > $PREFIX/data/setup_afids_data.sh.temp
    - mv -f $PREFIX/data/setup_afids_data.sh.temp $PREFIX/data/setup_afids_data.sh
    - cat $RECIPE_DIR/extra_for_setup $PREFIX/data/setup_afids_data.csh > $PREFIX/data/setup_afids_data.csh.temp
    - mv -f $PREFIX/data/setup_afids_data.csh.temp $PREFIX/data/setup_afids_data.csh
    - mkdir -p $PREFIX/etc/conda/activate.d
    - mkdir -p $PREFIX/etc/conda/deactivate.d
    - cp $RECIPE_DIR/scripts/activate.sh $PREFIX/etc/conda/activate.d/afids-data-activate.sh
    - cp $RECIPE_DIR/scripts/deactivate.sh $PREFIX/etc/conda/deactivate.d/afids-data-deactivate.sh
    # The symbolic links to external files seems to confuse conda, so replace
    # with dummy directories
    - rm $PREFIX/data/adrg
    - rm $PREFIX/data/cib1
    - rm $PREFIX/data/cib5
    - rm $PREFIX/data/landsat
    - rm $PREFIX/data/mars_kernel
    - rm $PREFIX/data/srtmL1_filled
    - rm $PREFIX/data/srtmL2_filled
    - rm $PREFIX/data/vmap1
    - rm $PREFIX/data/vdev/port_gaston_doq.img
    - rm $PREFIX/data/vdev/port_gaston_elv.hlf
    - rm $PREFIX/data/pommosdata/planet_dem
    - rm $PREFIX/data/pommosdata/testcases

requirements:
  build:
    - ${{ compiler('c') }}  
    # Don't really need cxx or fortran, but configure checks for this and
    # fails if it doesn't find it
    - ${{ compiler('cxx') }}  
    - ${{ compiler('fortran') }}
    - git
    - perl
    - patch
    - m4
    - make
  host:
  run:

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: This is AFIDS support data

