{% set name = "spice" %}
{% set version = "67.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  # Note we can't actually redistribute JPL spice because of licensing. But
  # we have scripts that download from the JPL site, so this mostly acts like
  # a conda package from the outside.
  # url: https://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Linux_GCC_64bit/packages/cspice.tar.Z

build:
  number: 2

requirements:
  build:
    - perl
    - patch
    - make
    - m4
  host:
  run:

about:
  home: https://naif.jpl.nasa.gov/naif/toolkit.html
  license: See https://naif.jpl.nasa.gov/naif/rules.html
  summary: 'NASA ancillary information system'

