context:
  name: afids
  version: 1.27

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: https://github.com/Cartography-jpl/${{ name }}.git
    tag: ${{ version }}
    #rev: c2b0b2930982e121e152ca86df5282c49df677ed
    target_directory: afids
    # Spice is a little complicated, because of the licensing. We can download
    # and link against this, and then distribute the package. But we can't redistribute
    # the spice library. So we go ahead and download when we build, and then use the
    # packages that we have built without including the libraries directly in conda
    # rattler-build Doesn't support .Z files yet, so we handle this below in the build
    # script
    #- url: https://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Linux_GCC_64bit/packages/cspice.tar.Z
    #  target_directory: cspice
    

build:
  number: 0
  script:
    - if: linux
      then: curl -k -L https://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Linux_GCC_64bit/packages/cspice.tar.Z | tar -xz -C ./
    - if: osx
      then: curl -k -L https://naif.jpl.nasa.gov/pub/naif/toolkit//C/MacM1_OSX_clang_64bit/packages/cspice.tar.Z | tar -xz -C ./
    - ln -s ./cspice.a cspice/lib/libcspice.a
    - ln -s ./csupport.a cspice/lib/libcsupport.a
    - mkdir afids/build
    - cd afids/build
    - ../configure --prefix="$PREFIX" --with-spice=$SRC_DIR/cspice --with-hdfeos=$PREFIX
    - make -j$CPU_COUNT all
    - make install
    - rm $PREFIX/setup_afids_env.sh
    - rm $PREFIX/setup_afids_env.csh
    - echo "conda_prefix=$PREFIX" > $PREFIX/setup_afids_env.sh
    - cat $RECIPE_DIR/setup_afids_env.sh >> $PREFIX/setup_afids_env.sh
    - echo "setenv conda_prefix $PREFIX" > $PREFIX/setup_afids_env.csh
    - cat $RECIPE_DIR/setup_afids_env.csh >> $PREFIX/setup_afids_env.csh
    - mkdir -p $PREFIX/etc/conda/activate.d
    - mkdir -p $PREFIX/etc/conda/deactivate.d
    - cp $RECIPE_DIR/afids-activate.sh $PREFIX/etc/conda/activate.d/afids-activate.sh
    - cp $RECIPE_DIR/afids-deactivate.sh $PREFIX/etc/conda/deactivate.d/afids-deactivate.sh
    
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - git
    - perl
    - patch
    - make
    - m4
    - pkg-config
  host:
    - afids-data
    - vicar
    - gdal
    - libgdal
    - boost ${{ boost }}
    - afids-carto
    - blas
    - vicar-rtl
    - tix
    - itcl
    - tk
    - gsl
    - hdfeos2
    - geotiff
    - fftw
    - vicar-gdalplugin
    - afids-xvd
    - gnuplot
    - libtirpc
  run:
    - afids-data
    - vicar 
    - gdal
    - libgdal
    - boost ${{ boost }}
    - afids-carto
    - blas
    - vicar-rtl
    - tix
    - itcl
    - tk
    - gsl
    - hdfeos2
    - geotiff
    - fftw
    - vicar-gdalplugin
    - gnuplot
    - libtirpc
    
about:
  license: BSD-3-Clause
  license_file:
    - afids/LICENSE
  summary: This is AFIDS.

